name: next Deployment
on:
  push:
    branches: [production]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD}}
          script: |
            cd /root/services/hrsystem
            git fetch origin 
            git checkout production
            git pull
            docker compose -p hrmanagement down
            docker compose -p hrmanagement up -d --build